# .readthedocs.yml

version: 2

python:
  version: 3.7
  install:
    - method: pip
      path: .
    - requirements: requirements.txt
    - requirements: docs/requirements.txt

# Build all formats
formats: all
